### ISSUE TITLE
Error in invoke method 'int java.lang.Integer.intValue()' on a null object reference

### ISSUE THREAD

**Issue by pbehin** [Gurgen/SignalR-.net-core-android-client#11]
https://github.com/Gurgen/SignalR-.net-core-android-client/blob/1af032a4871184e1570e3171b1abcc69b557d717/dotnetcoresignalrclientjava/src/main/java/com/smartarmenia/dotnetcoresignalrclientjava/WebSocketHubConnectionP2.java#L144

in some situation "element" variable is null(for example when variable m = {}).
It seems this variable should be checked before call getType method.

thanks

**Comment by pbehin** [comment]
Thank you for reply.
What time will the next version release? Is there any road map?

**Comment by Gurgen** [comment]
I hope next week

**Comment by Gurgen** [comment]
Error fixed
