### ISSUE TITLE
facing problem while getting large JSON response

### ISSUE THREAD

**Issue by devnathjha** [Gurgen/SignalR-.net-core-android-client#14]
we have developed Android client with the help of .net core signalr, Connected successfully, and getting the string and small json message succussfully but if json having image or large JSON contents then getting nothing. getting this {"type":6} continuously. While at the same time .Net client is able to connect and getting all the message successfully.

**Comment by IamEgor** [comment]
Update the websocket dependency from  
implementation 'org.java-websocket:Java-WebSocket:1.3.4' to 
implementation 'org.java-websocket:Java-WebSocket:1.3.8'
It worked for me

**Comment by devnathjha** [comment]
Yes it worked for me .
Thanks a lot @ IamIgore

**Comment by Gurgen** [comment]
Thanks to @devnathjha , @IamEgor 
I will update new lib to maven
