### ISSUE TITLE
Trust anchor for certification path not found. SSL

### ISSUE THREAD

**Issue by loidoantitan** [Gurgen/SignalR-.net-core-android-client#16]
Hi,
I can't connect socket SignIR. Error : javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

How are you config SSL . Please !

Thanks

**Comment by reverseAndroid** [comment]
我将证书导入手机中，但是还是会出现这个错误，请问你解决了嘛？
