### ISSUE TITLE
Timed out exception from android client

### ISSUE THREAD

**Issue by isairuiz** [Gurgen/SignalR-.net-core-android-client#2]
Hi, recently i'm trying to connect a signalr android client to my .net core server but im getting a Timed out exception this is the stack from android studio:
`10-17 15:38:12.524 25915-25931/com.ruizsoft.testandroidsignalr W/System.err: java.net.SocketTimeoutException: connect timed out
10-17 15:38:12.524 25915-25931/com.ruizsoft.testandroidsignalr W/System.err:     at java.net.PlainSocketImpl.socketConnect(Native Method)
10-17 15:38:12.525 25915-25931/com.ruizsoft.testandroidsignalr W/System.err:     at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
10-17 15:38:12.525 25915-25931/com.ruizsoft.testandroidsignalr W/System.err:     at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
10-17 15:38:12.525 25915-25931/com.ruizsoft.testandroidsignalr W/System.err:     at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
10-17 15:38:12.525 25915-25931/com.ruizsoft.testandroidsignalr W/System.err:     at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
10-17 15:38:12.525 25915-25931/com.ruizsoft.testandroidsignalr W/System.err:     at java.net.Socket.connect(Socket.java:586)
10-17 15:38:12.525 25915-25931/com.ruizsoft.testandroidsignalr W/System.err:     at com.android.okhttp.internal.Platform.connectSocket(Platform.java:113)
10-17 15:38:12.525 25915-25931/com.ruizsoft.testandroidsignalr W/System.err:     at com.android.okhttp.Connection.connectSocket(Connection.java:196)
10-17 15:38:12.525 25915-25931/com.ruizsoft.testandroidsignalr W/System.err:     at com.android.okhttp.Connection.connect(Connection.java:172)
10-17 15:38:12.525 25915-25931/com.ruizsoft.testandroidsignalr W/System.err:     at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367)
10-17 15:38:12.525 25915-25931/com.ruizsoft.testandroidsignalr W/System.err:     at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
10-17 15:38:12.525 25915-25931/com.ruizsoft.testandroidsignalr W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:329)
10-17 15:38:12.525 25915-25931/com.ruizsoft.testandroidsignalr W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:246)
10-17 15:38:12.525 25915-25931/com.ruizsoft.testandroidsignalr W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
10-17 15:38:12.525 25915-25931/com.ruizsoft.testandroidsignalr W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405)
10-17 15:38:12.525 25915-25931/com.ruizsoft.testandroidsignalr W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:521)
10-17 15:38:12.525 25915-25931/com.ruizsoft.testandroidsignalr W/System.err:     at com.smartarmenia.dotnetcoresignalrclientjava.WebSocketHubConnection.getConnectionId(WebSocketHubConnection.java:83)
10-17 15:38:12.525 25915-25931/com.ruizsoft.testandroidsignalr W/System.err:     at com.smartarmenia.dotnetcoresignalrclientjava.WebSocketHubConnection.access$000(WebSocketHubConnection.java:27)
10-17 15:38:12.525 25915-25931/com.ruizsoft.testandroidsignalr W/System.err:     at com.smartarmenia.dotnetcoresignalrclientjava.WebSocketHubConnection$1.run(WebSocketHubConnection.java:56)
10-17 15:38:12.525 25915-25931/com.ruizsoft.testandroidsignalr W/System.err:     at java.lang.Thread.run(Thread.java:761)`

I have checked that my server is accessible from outside(mobile browser) and there is no problem, here is my server code:

**Chat Hub**
`public class Chat:Hub`
 `   {`
 `     public Task Send(string message)`
 `   {`
 `     return Clients.All.InvokeAsync("Send", message);`
     `}`
 `   }`

My **startup.cs**
`services.AddSignalR();`
`app.UseSignalR(routes => `
            `{`
               ` routes.MapHub<Chat>("chat");`
            `});`

And my **java code**:
`public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        String authHeader = "Bearer ISTHISREALLYNEEDED";
        HubConnection connection = new WebSocketHubConnection("http://192.160.100.79:63980/chat",authHeader);

        connection.addListener(new HubConnectionListener() {
            @Override
            public void onConnected() {
                Log.e("ON CONNECTED","Me me conecte al server...ok");
            }

            @Override
            public void onDisconnected() {
                Log.e("ON DISCONNECTED","Me me desconecte del server...ok");
            }

            @Override
            public void onMessage(HubMessage message) {
                Log.e("ON MESSAGE",message.getArguments().toString());
            }

            @Override
            public void onError(Exception exception) {
                Log.e("ON ERROR",exception.toString());
            }
        });
        connection.subscribeToEvent("send", new HubEventListener() {
            @Override
            public void onEventMessage(HubMessage message) {
                Log.e("ON EVENT MESSAGE", message.getArguments().toString());
            }
        });
        connection.connect();

    }
}`

**Comment by Gurgen** [comment]
What is the response on browser when you open URL [http://192.160.100.79:63980/chat](http://192.160.100.79:63980/chat) ?

**Comment by isairuiz** [comment]
[Here](https://user-images.githubusercontent.com/4392363/31691057-503758ce-b35a-11e7-9e81-be567a32677e.PNG) is the screenshot from simulator debug check it please.

**Comment by Gurgen** [comment]
Try open on phone/emulator's browser hub link [http://192.160.100.79:63980/chat](http://192.160.100.79:63980/chat)

**Comment by isairuiz** [comment]
You're going to kill me!!!, I realized that the ip is wrong, sorry for taking your time, I have spent too much time on this sorry. 🤕

**Comment by Gurgen** [comment]
192.160 :D

No problem )))
