### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by hezhipengzipp** [Gurgen/SignalR-.net-core-android-client#3]
I use this progrom, java.lang.RuntimeException: Server error, can you tell me ,how to detail with it

**Comment by Gurgen** [comment]
Can you show code. How do you connect?

**Comment by santhoshpulliman** [comment]
Getting same error, below is my code
`public class MainActivity extends AppCompatActivity implements HubConnectionListener, HubEventListener {
    public static final String PPVIDEO_CONNECT_URL = "http://192.168.26.214/";
    private WebSocketHubConnection connection;
    private ServerConnection mServerConnection;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        connection = new WebSocketHubConnection(PPVIDEO_CONNECT_URL, "");
        connection.connect();
        connection.addListener(this);
        connection.subscribeToEvent("System", this);

    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        connection.disconnect();
    }

    @Override
    public void onConnected() {
        System.out.println("Signalr Connected");
    }

    @Override
    public void onDisconnected() {
        System.out.println("Signalr Disconnected");
    }

    @Override
    public void onMessage(HubMessage message) {
        System.out.println("Signalr Message: " + message);
    }

    @Override
    public void onError(Exception exception) {
        System.out.println("Signalr exception: " + exception);
    }

    @Override
    public void onEventMessage(HubMessage message) {
        System.out.println("Event Message: " + message.getArguments().toString());
    }`

**Comment by Gurgen** [comment]
Can you debug connect process and tell me line from where throws RunTimeException?

**Comment by santhoshpulliman** [comment]
In WebSocketHubConnection.java line number 160. that is  'onError'callback of WebSocketClient

**Comment by Gurgen** [comment]
And what is exception? There is a ex param

**Comment by santhoshpulliman** [comment]
some issues in the url. now onClosed callback is invoked. so might be issue at the server. Thanks for the reply

**Comment by Gurgen** [comment]
Yes, I think issue on server side, but if any problems, please write here

**Comment by santhoshpulliman** [comment]
I am facing an issue when the SignalR server is hosted in Azure. Locally hosted server code is working fine.
HubConnectionListener.onDisconnected() is invoked. The azure hosted thing is working fine in javascript SDK but not in Android

**Comment by Gurgen** [comment]
Can you provide me your azure host address, I will check?

**Comment by Gurgen** [comment]
Thank you @santhoshpulliman , fixed

**Comment by yousefbeiruty** [comment]
I am having the same  issue @Gurgen  how can i solve it the backend can connected successfully but i cant??

here is my code:-

 /** TODO:-SignalR Fields*/

    val parentJob = Job()
    val handler = CoroutineExceptionHandler { _, exception ->
        println("Caught $exception")
        Timber.tag("KotlinMainActivity").d("Caught $exception")
    }
    val coroutineScope = CoroutineScope(Dispatchers.IO + parentJob + handler)
    val url="https://sdemo2.numny.com/apisignalr"
    private  val  connection = WebSocketHubConnectionP2(url, getCachedToken())

 public override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

  /** TODO:-Connect to SignalR */
        connection.addListener(this@KotlinMainActivity)
        connection.subscribeToEvent(EVENT_NAME, this)
        connect()
        sendMessage()

}

/** TODO:-SignalR Methods*/
    override fun onEventMessage(message: HubMessage) {
        coroutineScope.launch {
            Log.d(TAG, "Event message: ${message.target}\n${Gson().toJson(message.arguments)}")
            withContext(Dispatchers.Main) {
                Toast.makeText(
                    this@KotlinMainActivity,
                    "Event message: ${message.target}\n${Gson().toJson(message.arguments)}",
                    Toast.LENGTH_SHORT
                ).show()
            }
        }
    }

    override fun onConnected() {
        coroutineScope.launch {
            Log.d(TAG, "Connected")
            withContext(Dispatchers.Main) {
                Toast.makeText(this@KotlinMainActivity, "Connected", Toast.LENGTH_SHORT).show()
            }
        }
    }

    override fun onDisconnected() {
        coroutineScope.launch {
            Log.d(TAG, "Disconnected")
            withContext(Dispatchers.Main) {
                Toast.makeText(this@KotlinMainActivity, "Disconnected", Toast.LENGTH_SHORT).show()
            }
        }
    }

    override fun onMessage(message: HubMessage) {
        coroutineScope.launch {
            Log.d(TAG, "onMessage:\"${message.target}\\n${Gson().toJson(message.arguments)}\"")
            withContext(Dispatchers.Main) {
                Toast.makeText(
                    this@KotlinMainActivity,
                    "${message.target}\n${Gson().toJson(message.arguments)}",
                    Toast.LENGTH_SHORT
                ).show()
            }
         }
    }

    override fun onError(exception: Exception) {
        coroutineScope.launch {
            Log.d(TAG, "onError: ${exception.message}")
            exception.printStackTrace()
            withContext(Dispatchers.Main) {
                Toast.makeText(this@KotlinMainActivity, exception.message, Toast.LENGTH_SHORT)
                    .show()
            }
        }
    }


     fun  sendMessage(){
        try {
             Log.d(TAG, "sendMessage")
             connection.invoke(EVENT_NAME, 9 , getProgramNumber(), getPosID(), getPosUserID(),getCachedToken(),18)
        } catch (e: Exception) {
            Log.d(TAG, "sendMessage: Exception: ${e.message}")
            e.printStackTrace()
            Toast.makeText(this@KotlinMainActivity, e.message, Toast.LENGTH_SHORT).show()
        }
    }


    fun connect() {
        try {
            connection.connect()
        } catch (ex: Exception) {
            coroutineScope.launch  {
                Log.d(TAG, "connect: ${ex.cause}")
                ex.printStackTrace()
                withContext(Dispatchers.Main) {
                    Toast.makeText(this@KotlinMainActivity, ex.message, Toast.LENGTH_SHORT).show()
                }
            }
        }
    }
