### ISSUE TITLE
Not able to connect with hub on azure saying server error

### ISSUE THREAD

**Issue by ravi-shaw** [Gurgen/SignalR-.net-core-android-client#4]
I have created a simple signalr hub(ChatHub) with no authentication and deployed it to azure cloud. Given a domain name as well(http://doxpe.com). Now I am trying to connect with signalr hub via android app using this library. I have given the hub url as http://doxpe.com/signalr. But I am not able to connect with the hub. Its saying server error. While at the same time .Net client is able to connect with the hub using the same url. Please suggest do I need to do something extra.

I have even tried the sample app given by you and changed the url with the above url. Sample app also is not able to connect saying same error.

**Comment by Gurgen** [comment]
What is the version of your signalr server?

**Comment by Gurgen** [comment]
This library for .net core version of signal r. As I understand your server is .net framework. .net core and .net framework signal r are absolutely different. Please use library for framework version.
[https://github.com/SignalR/java-client](https://github.com/SignalR/java-client)

**Comment by ravi-shaw** [comment]
ok. I am using .net signalr. Got it. Thanks Gurgen.................
