### ISSUE TITLE
connection not established

### ISSUE THREAD

**Issue by mjhasani** [Gurgen/SignalR-.net-core-android-client#5]
Dear Gurgen,
I used this library as below:

 WebSocketHubConnection mHubConnection = new WebSocketHubConnection("https://...", null);
        mHubConnection.addListener(new HubConnectionListener() {
            @Override
            public void onConnected() {
                Log.d("websocket","connected");
            }

            @Override
            public void onDisconnected() {
                Log.d("websocket","disconnected");
            }

            @Override
            public void onMessage(HubMessage message) {
                Log.d("websocket","message");
            }

            @Override
            public void onError(Exception exception) {
                Log.d("websocket","error");
            }
        });
        mHubConnection.connect();

but no connection established and onconnect method not called.
The console logs are as:

I/WebSockets: Requesting connection id...
E/EGL_emulation: tid 4904: eglSurfaceAttrib(1261): error 0x3009 (EGL_BAD_MATCH)
W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0x8c76f220, error=EGL_BAD_MATCH
I/WebSockets: Connecting...
D/EGL_emulation: eglMakeCurrent: 0xa2a840c0: ver 2 0 (tinfo 0xa2a83720)
I/WebSockets: Closed. Code: -1, Reason: , Remote: true
D/websocket: disconnected

Thanks.

**Comment by Gurgen** [comment]
Update to version v1.10 and try again

**Comment by meisamhasani** [comment]
Where is the link to this version?

**Comment by mjhasani** [comment]
Its ok.
Thanks.
