### ISSUE TITLE
server error response with code 400

### ISSUE THREAD

**Issue by paularevalo** [Gurgen/SignalR-.net-core-android-client#6]
I get always  this error when trying to connect to my hub. http://myip:myport/signalr/hubs/myhub.

**Comment by Gurgen** [comment]
Hi. This is bad request error. What is error message?

**Comment by paularevalo** [comment]
Protocol error: Unknown transport.

**Comment by Gurgen** [comment]
Is working your server with javascript client?

**Comment by paularevalo** [comment]
yes, when its on //SignalR/hubs:

/*!
 * ASP.NET SignalR JavaScript Library v2.2.2
 * http://signalr.net/
 *
 * Copyright (c) .NET Foundation. All rights reserved.
 * Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
 *
 */

/// <reference path="..\..\SignalR.Client.JS\Scripts\jquery-1.6.4.js" />
/// <reference path="jquery.signalR.js" />
(function ($, window, undefined) {
    /// <param name="$" type="jQuery" />
    "use strict";

    if (typeof ($.signalR) !== "function") {
        throw new Error("SignalR: SignalR is not loaded. Please ensure jquery.signalR-x.js is referenced before ~/signalr/js.");
    }

    var signalR = $.signalR;

    function makeProxyCallback(hub, callback) {
        return function () {
            // Call the client hub method
            callback.apply(hub, $.makeArray(arguments));
        };
    }

    function registerHubProxies(instance, shouldSubscribe) {
        var key, hub, memberKey, memberValue, subscriptionMethod;

        for (key in instance) {
            if (instance.hasOwnProperty(key)) {
                hub = instance[key];

                if (!(hub.hubName)) {
                    // Not a client hub
                    continue;
                }

                if (shouldSubscribe) {
                    // We want to subscribe to the hub events
                    subscriptionMethod = hub.on;
                } else {
                    // We want to unsubscribe from the hub events
                    subscriptionMethod = hub.off;
                }

                // Loop through all members on the hub and find client hub functions to subscribe/unsubscribe
                for (memberKey in hub.client) {
                    if (hub.client.hasOwnProperty(memberKey)) {
                        memberValue = hub.client[memberKey];

                        if (!$.isFunction(memberValue)) {
                            // Not a client hub function
                            continue;
                        }

                        subscriptionMethod.call(hub, memberKey, makeProxyCallback(hub, memberValue));
                    }
                }
            }
        }
    }

    $.hubConnection.prototype.createHubProxies = function () {
        var proxies = {};
        this.starting(function () {
            // Register the hub proxies as subscribed
            // (instance, shouldSubscribe)
            registerHubProxies(proxies, true);

            this._registerSubscribedHubs();
        }).disconnected(function () {
            // Unsubscribe all hub proxies when we "disconnect".  This is to ensure that we do not re-add functional call backs.
            // (instance, shouldSubscribe)
            registerHubProxies(proxies, false);
        });

        proxies['endUsersHub'] = this.createHubProxy('endUsersHub'); 
        proxies['endUsersHub'].client = { };
        proxies['endUsersHub'].server = {
        };

        proxies['guardsHub'] = this.createHubProxy('guardsHub'); 
        proxies['guardsHub'].client = { };
        proxies['guardsHub'].server = {
        };

        proxies['logicEngineHub'] = this.createHubProxy('logicEngineHub'); 
        proxies['logicEngineHub'].client = { };
        proxies['logicEngineHub'].server = {
            heartbeat: function () {
                return proxies['logicEngineHub'].invoke.apply(proxies['logicEngineHub'], $.merge(["Heartbeat"], $.makeArray(arguments)));
             },

            notifyBackOfficeEndOfServiceVerified: function (message, operatorUserName, endUserEmail) {
                return proxies['logicEngineHub'].invoke.apply(proxies['logicEngineHub'], $.merge(["NotifyBackOfficeEndOfServiceVerified"], $.makeArray(arguments)));
             },

            notifyEventCandidacyAcceptance: function (guardUserName, eventKey, message) {
                return proxies['logicEngineHub'].invoke.apply(proxies['logicEngineHub'], $.merge(["NotifyEventCandidacyAcceptance"], $.makeArray(arguments)));
             },

            notifyEventCandidacyDismissal: function (guardUserName, eventKey, message) {
                return proxies['logicEngineHub'].invoke.apply(proxies['logicEngineHub'], $.merge(["NotifyEventCandidacyDismissal"], $.makeArray(arguments)));
             },

            notifyEventMovilizationStarted: function (endUserEmail, operatorUserName, message) {
                return proxies['logicEngineHub'].invoke.apply(proxies['logicEngineHub'], $.merge(["NotifyEventMovilizationStarted"], $.makeArray(arguments)));
             },

            notifyEventOperatorAssignmentToBackOffice: function (message, operatorUserName) {
                return proxies['logicEngineHub'].invoke.apply(proxies['logicEngineHub'], $.merge(["NotifyEventOperatorAssignmentToBackOffice"], $.makeArray(arguments)));
             },

            notifyForcedCloseEventCompleted: function (eventId) {
                return proxies['logicEngineHub'].invoke.apply(proxies['logicEngineHub'], $.merge(["NotifyForcedCloseEventCompleted"], $.makeArray(arguments)));
             },

            notifyGuardEndOfService: function (endUserEmail, operatorUserName, message) {
                return proxies['logicEngineHub'].invoke.apply(proxies['logicEngineHub'], $.merge(["NotifyGuardEndOfService"], $.makeArray(arguments)));
             },

            notifyGuardLocation: function (endUserEmail, operatorUserName, message) {
                return proxies['logicEngineHub'].invoke.apply(proxies['logicEngineHub'], $.merge(["NotifyGuardLocation"], $.makeArray(arguments)));
             },

            notifyGuardSelection: function (eventId, endUserEmail, guardUserName, operatorUserName, message) {
                return proxies['logicEngineHub'].invoke.apply(proxies['logicEngineHub'], $.merge(["NotifyGuardSelection"], $.makeArray(arguments)));
             },

            notifyNewEventToBackOffice: function (event, message) {
                return proxies['logicEngineHub'].invoke.apply(proxies['logicEngineHub'], $.merge(["NotifyNewEventToBackOffice"], $.makeArray(arguments)));
             },

            notifyNewEventToCandidates: function (event, message) {
                return proxies['logicEngineHub'].invoke.apply(proxies['logicEngineHub'], $.merge(["NotifyNewEventToCandidates"], $.makeArray(arguments)));
             },

            notifyServiceRated: function (eventId, operatorUserName) {
                return proxies['logicEngineHub'].invoke.apply(proxies['logicEngineHub'], $.merge(["NotifyServiceRated"], $.makeArray(arguments)));
             },

            notifyServiceStarted: function (endUserEmail, operatorUserName, message) {
                return proxies['logicEngineHub'].invoke.apply(proxies['logicEngineHub'], $.merge(["NotifyServiceStarted"], $.makeArray(arguments)));
             },

            notifyUpcomingEventWithoutCandidatesAlert: function (event, message) {
                return proxies['logicEngineHub'].invoke.apply(proxies['logicEngineHub'], $.merge(["NotifyUpcomingEventWithoutCandidatesAlert"], $.makeArray(arguments)));
             },

            notifyUpcomingEventWithoutGuardAlert: function (event, message) {
                return proxies['logicEngineHub'].invoke.apply(proxies['logicEngineHub'], $.merge(["NotifyUpcomingEventWithoutGuardAlert"], $.makeArray(arguments)));
             },

            notifyUpcomingEventWithoutOperatorAlert: function (event, message) {
                return proxies['logicEngineHub'].invoke.apply(proxies['logicEngineHub'], $.merge(["NotifyUpcomingEventWithoutOperatorAlert"], $.makeArray(arguments)));
             },

            sendSimpleMessageToBackOffice: function (message, operatorUserName) {
                return proxies['logicEngineHub'].invoke.apply(proxies['logicEngineHub'], $.merge(["SendSimpleMessageToBackOffice"], $.makeArray(arguments)));
             }
        };

        proxies['operatorHub'] = this.createHubProxy('operatorHub'); 
        proxies['operatorHub'].client = { };
        proxies['operatorHub'].server = {
            test: function (val) {
                return proxies['operatorHub'].invoke.apply(proxies['operatorHub'], $.merge(["Test"], $.makeArray(arguments)));
             }
        };

        return proxies;
    };

    signalR.hub = $.hubConnection("/signalr", { useDefaultPath: false });
    $.extend(signalR, signalR.hub.createHubProxies());

}(window.jQuery, window));

**Comment by Gurgen** [comment]
Is your server .net core?
This library for .net core signalR server, not for Asp.net signalR.

**Comment by Gurgen** [comment]
#4 Here same error discussed
