### ISSUE TITLE
405 Method Not Allowed when connecting

### ISSUE THREAD

**Issue by davenewza** [Gurgen/SignalR-.net-core-android-client#7]
When connecting to our SignalR ASP.NET Core hub it throws an exception with message "Server error" ([from here](https://github.com/Gurgen/SignalR-.net-core-android-client/blob/develop/dotnetcoresignalrclientjava/src/main/java/com/smartarmenia/dotnetcoresignalrclientjava/WebSocketHubConnection.java#L103)).  Upon inspection, a HTTP 405 Method Not Allowed is returned from the server.

        HubConnection connection = new WebSocketHubConnection("http://precariouswebsockets.azurewebsites.net/user", null);
        connection.connect();

I am able to connect to this fine from my local C# client.

Judging from https://github.com/aspnet/SignalR/issues/1400 it could be a incompatibility issue?

Note: we are using `Microsoft.AspNetCore.SignalR 1.0.0-preview1-final`

**Comment by davenewza** [comment]
That hub is up and running so you are welcome to try.  There is a method called "Accept" which takes in a string as its single parameter.

**Comment by Gurgen** [comment]
Please check your server code, and try connect to hub with JavaScript client. If same problem, fix server.

**Comment by davenewza** [comment]
We are able to connect to the server using Javascript and C# clients, just not with this Java client.

**Comment by Gurgen** [comment]
Can you send me link of web page of success connect to server?

**Comment by akasyanchuk** [comment]
I also tried to use your library but faced with the same error 405. The SignalR protocol has changed in .Net Core 2.1 Preview 1 (2.1.300-preview1-008174). I examined official SignalR sources (typescript client) and tried to do the same in Java - It works. So, please check the approach to do handshake request through websocket connection (you don't need to send OPTIONS request anymore) and change your sources accordingly.
Thanks.

**Comment by Gurgen** [comment]
Thank you @akasyanchuk , I will change and will test all for new changes.
If you want and have time, you can do that here and create PR, otherwise I will do it.

**Comment by akasyanchuk** [comment]
@kortgat if you want to make this client work you need to change some logic. I examined official SignalR Core typescript client sources and there found how I need to develop the client. (I haven't used this client yet but I investigated why this client doesn't work)

**Comment by Gurgen** [comment]
@kortgat Can you please tell which javascript version are you using?

**Comment by Gurgen** [comment]
OK, preparing new version for preview2-final server version

**Comment by kortgat** [comment]
Thank You!! You will save me a lot of time.

**Comment by Gurgen** [comment]
Done, please check if any problems, write here.

**Comment by kortgat** [comment]
It is working for my use thank you I appreciate :)
